spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql:///scheduling2?serverTimezone=Asia/Shanghai

  jpa:
    database-platform: mysql
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect